default_language_version:
  python: python3
repos:
  # needs python 3.6+

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        exclude: ^(markupsafe/|requests/|urllib3/)
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.9.3"
    hooks:
      - id: isort
        exclude: ^(markupsafe/|requests/|urllib3/)
        args: ["--profile", "black"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^(markupsafe|requests|urllib3|\.git.*|__pycache__|tests)
